schema: schema.graphql
documents:
  - "examples/test/**/*.graphql"
  - "examples/test/**/*.{ts,tsx}"
extensions:
  endpoints:
    default: https://graphql-pokemon.now.sh
  codegen:
    scalars:
      DateTime: Date
    overwrite: true
